# This is a basic workflow to help you get started with Actions

name: Workflow

# Controls when the workflow will run
on:
  #  # Triggers the workflow on push or pull request events but only for the "main" branch
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]

  # Shedule 1 fois par semaine
  schedule:
    - cron: "0 14 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github-pipeline-library:
    uses: laveracloudsolutions/github-pipeline-library/.github/workflows/build.yml@main
    with:
      config-path: .github/images.json
    secrets: inherit